configuration:
    static_dir: assets  # Static directory.
    build_dir: build
    template_dir: templates

pages:
    - filename: index.html
      template: default.html
      content: content/index.html

    - filename: extinction.html
      template: default.html
      content: content/extinction.html

    - filename: reflections.html
      template: default.html
      content: content/reflections.html

    - filename: synthese.html
      template: default.html
      content: content/synthese.html

    - filename: adventure-island.html
      template: default.html
      content: content/adventure-island.html
