configuration:
    static_dir: assets  # Static directory.
    build_dir: build
    template_dir: templates

pages:
    - filename: index.html
      template: default.html
      content: content/index.html

    - filename: extinction.html
      template: default.html
      content: content/extinction.html

    - filename: reflections.html
      template: default.html
      content: content/reflections.html

    - filename: adventure_island.html
      template: default.html
      content: content/adventure_island.html

    - filename: hereafter.html
      template: default.html
      content: content/hereafter.html
